### PR TITLE
Change name of currentSong function

### PR DESCRIPTION
**Pull request by MowAlon**
#### What's this PR do?
The currentSong function only reports back whether or not a song has started, so I changed the name to songHasStarted
#### Where should the reviewer start?
Check all files in the repo to confirm the old name, currentSong, is no longer used anywhere in the code. Silver Searcher, 'ag' search, is good for that.
#### How should this be manually tested?
If it's broken, I'm pretty sure the game won't run properly, so just try to play!
#### What gif best describes this PR or how it makes you feel?

@stevekinney

### CODE REVIEW

**Comment by MowAlon** [comment]
@mbburch

**Comment by russelleh** [comment]
Looking good. Thanks for the fix.

**Comment by russelleh** [comment]
:train: :boat: :car:

**Comment by rrgayhart** [comment]
:+1:

**Pull request merged**
